---
- hosts: localhost
  name: Use terraform to create a VM and install puppet on it
  tasks:
    - name: Include VM creation task
      ansible.builtin.include_tasks:
        file: tasks/spin_vm_task.yml
- name: Import puppet agent configuration play book
  ansible.builtin.import_playbook: tasks/puppet_playbook.yml

- name: Import puppetserver CA signing playbook
  ansible.builtin.import_playbook: tasks/ca_signing.yml


